### ISSUE TITLE
Non-linear interpolation

### ISSUE THREAD

**Issue by LeaVerou** [color-js/color.js#12]
Right now we only support linear interpolation.

We should also support:

- [ ] Custom cubic bezier
- [ ] Possibly keywords
- [x] Entirely custom functions

**Comment by svgeesus** [comment]
Interpolation with curves can produce out of gamut values due to curve overshoot. It is desirable to minimize this, and come curve interpolation methods have no overshoot.

[This overview of interpolation](http://paulbourke.net/miscellaneous/interpolation/) mentions cosine interpolation, which is very straightforward code-wise and avoids the obvious discontinuities produced by linear interpolation, while having no overshoot:

![linear](http://paulbourke.net/miscellaneous/interpolation/linear.gif)
![cosine](http://paulbourke.net/miscellaneous/interpolation/cosine.gif)

**Comment by svgeesus** [comment]
compare

```c
double LinearInterpolate(
   double y1,double y2,
   double mu)
{
   return(y1*(1-mu)+y2*mu);
}
```

with

```c
double CosineInterpolate(
   double y1,double y2,
   double mu)
{
   double mu2;

   mu2 = (1-cos(mu*PI))/2;
   return(y1*(1-mu2)+y2*mu2);
}
```

**Comment by LeaVerou** [comment]
Closing this since we already have non-linear-interpolation, and opened #410 to track shortcuts
