### ISSUE TITLE
Add support for HCT color space

### ISSUE THREAD

**Issue by TaigaYamada** [color-js/color.js#223]
First of all, thank you for the amazing library.

Google developed a new color space named HCT, intended to be perceptually uniform.
[Here's a blog post introducing it.](https://material.io/blog/science-of-color-design)

(The blog post comparing HCT to OKLab directly when one is polar coordinates and the other is orthogonal is questionable, but that's all the more reason to get hands-on and test it out)

I'd love to experiment and work with this new color space, and having it available as part of the color.js would considerably empower designers with similar goals.

**Comment by Crissov** [comment]
> … HCT, which stands for hue, chroma, tone.
>
> …
>
> HCT’s lightness measure, tone, is the same as L*a*b*’s lightness.
> …
>
> HCT’s hue and colorfulness measures, hue and chroma, are the same as CAM16’s hue and chroma.

That is all?

**Comment by TaigaYamada** [comment]
Can CAM16's hue and chroma be altered while keeping lightness in terms of Lab intact? If that's the case I guess I can just use the functionalities already in the library

**Comment by LeaVerou** [comment]
Still, if anyone has the cycles, it would be nice to add HCT, for convenience.

**Comment by facelessuser** [comment]
> That is all?

That seems to be the basic idea, assuming you use the same viewing conditions. I think by default they base the adapting luminance and background luminance off of 50 L\* and assume an "average" surround.

> Can CAM16's hue and chroma be altered while keeping lightness in terms of Lab intact? If that's the case I guess I can just use the functionalities already in the library

This is the part I'm not so sure of. There is no easy conversion back to something like RGB just having HCT components, it seems to be quite involved. They seem to have a complex solver in the Material lib. If you have an HCT color and update Hue, you go through this solver and update the whole color (all channels).

I haven't really played with their lib though. I more just took an existing CAM16 implementation that I did, checked what their viewing conditions were, calculated the HCT values and compared it to their tests.

It seems simply getting to HCT is as easy as convert the given color to both CIELAB and CAM16 and extracting L\*, C, and h, but going back is a bit more complicated as you have components from two separate color spaces.

**Comment by facelessuser** [comment]
Just a little more information in case someone was looking to try and implement HCT. You can probably use https://observablehq.com/@jrus/cam16 as a general reference to get to CAM16. It's the same reference that Material's HCT article references. They don't really seem to have an article on how to get solve back from HCT, so I guess you'd have to use the Material repo as a reference: https://github.com/material-foundation/material-color-utilities, assuming the license is compatible.

Assuming a 50 L\*, we can calculate the XYZ `y` value and then calculate the adapting luminance as `200 / π * y` and the background luminance as `y * 100`. I guess if you scaled `y` by 100 from the start, you could just use `2 / π * y` and `y`. You also use average surround coefficients of `(1, 0.69, 1)` (f, c, nc).

Modifying a CAM16-UCS implementation to use the above viewing conditions and dumping the intermediate CAM16 values, we can compare our results to one of their tests.

The HCT lib test:

```js
describe('ARGB to HCT', () => {
  it('green', () => {
    const hct = Hct.fromInt(GREEN);
    expect(hct.hue).toBeCloseTo(142.139, 2);
    expect(hct.chroma).toBeCloseTo(108.410, 2);
    expect(hct.tone).toBeCloseTo(87.737, 2);
  });
```

And here are our calculations from our CAM16 and Lab D65 implementation. The results are only slightly different as they use a slightly different white point, but for all intents and purposes, it is the same.

```python
>>> Color('#00ff00').convert('cam16-ucs')
{'J': 79.32965041737212, 'C': 108.4064894320562, 'h': 142.1403801728313, 's': 78.60411557956203, 'Q': 138.5183412228265, 'M': 85.58503907747414, 'H': 177.11121792753474}
color(--cam16-ucs 86.71 -37.476 29.132 / 1)
>>> Color('#00ff00').convert('lab-d65')
color(--lab-d65 87.736 -86.182 83.187 / 1)
```

You can always easily get the proper `y` from an HCT color as the tone is equal to L\* which comes directly from XYZ `y` and doesn't consider `x` and `z` for that specific component translation back and forth. In reality, you don't have to calculate the entire Lab color space, all you need is the L\* value, so you could optimize it to only calculate to and from L\*.

So the tricky part is taking that `y` and figuring out what the CAM16 `J` value would be such that you get the current `H` and `C` values. At least that is my initial understanding. That's where the solver comes into play. I have not looked into how they specifically solve the reverse translation, this is only based on my current observations which are based on the translation to HCT.

Considering conversion to CAM16 is not cheap, and you have to go through the solver to get out of HCT, it seems like a fairly expensive color space to translate back and forth to. Since I haven't bothered to get a working translation out of HCT, and I haven't actually played with the reference library, I'm also not sure how precise round-tripping is either.

It was fairly easy to get to HCT only because I had already implemented CAM16, so implementing a full HCT color space is definitely not trivial.

**Comment by facelessuser** [comment]
So, I was able to get HCT conversion to and from sRGB working. It should be noted that the current method is fairly naive and uses simple bisecting to approximate the appropriate J for a given L* in an HCT color space so we can get back to sRGB. 

```py
>>> Color('green')
color(srgb 0 0.50196 0 / 1)
>>> Color('green').convert('hct')
color(--hct 142.23 71.136 46.228 / 1)
>>> Color('green').convert('hct').convert('srgb')
color(srgb 0 0.50196 0 / 1)
```

No doubt, the Material library uses far more tricks than a simple bisect to shortcut back to sRGB, but this basic logic made it possible for me to do a basic test and render the HCT color space in the sRGB gamut.

![hct](https://user-images.githubusercontent.com/1055125/214097657-047d72d8-cb43-4630-b009-eece29eca3d7.png)

Something to note though, when converting, the chroma minimum and maximum range can vary depending on the hue. You can have a chroma as large as 2.x for an achromatic value. If you try and set that chroma to zero, you will likely end up with a non-achromatic color. Ideally, you would have some kind of way to easily calculate the low-end chroma for a given hue so you could rein it in when converting back to sRGB.

The Material lib seems to go much further than that and only allows certain steps of chroma to be set. They seem to be managing this stuff a lot, but I haven't looked into how they enforce this. You can see when trying to set chroma in their library, it is very strictly managed. This is most likely to make things even faster, but I don't think it is strictly necessary.

Here we try to use the Material library to set an achromatic value. We'll try and lower the chroma, but you can see it stops that from happening. In fact, it won't change the hue until it gets big enough to be close to the next chroma step, and then changes once again are locked to that step. Nothing really wrong with the approach, just interesting. They clearly had goals of tightly tying this to sRGB, and probably to sRGB hex codes more specifically.

```js
> var c = hct.Hct.fromInt(0xff888888)
undefined
> hct.Hct.from(c.hue, 0, c.tone)
Hct {
  argb: 4287137928,
  internalHue: 209.49370704453193,
  internalChroma: 1.9658313307778987,
  internalTone: 56.70341075675441
}
> hct.Hct.from(c.hue, 2, c.tone)
Hct {
  argb: 4287137928,
  internalHue: 209.49370704453193,
  internalChroma: 1.9658313307778987,
  internalTone: 56.70341075675441
}
> hct.Hct.from(c.hue, 2.3, c.tone)
Hct {
  argb: 4287137928,
  internalHue: 209.49370704453193,
  internalChroma: 1.9658313307778987,
  internalTone: 56.70341075675441
}
> hct.Hct.from(c.hue, 2.5, c.tone)
Hct {
  argb: 4287072392,
  internalHue: 206.0031566661484,
  internalChroma: 2.625063364851419,
  internalTone: 56.62128000508153
}
> hct.Hct.from(c.hue, 2.8, c.tone)
Hct {
  argb: 4287072392,
  internalHue: 206.0031566661484,
  internalChroma: 2.625063364851419,
  internalTone: 56.62128000508153
}
```

Anyways, just posting here in case this information is useful.

**Comment by facelessuser** [comment]
Just to clarify, the hue affecting minimum chroma is there, but probably is a very small contributor, it seems lightness contributes much more.

**Comment by facelessuser** [comment]
Seems the response is linear making it really easy to detect when a color is achromatic. It scales by `t * 2.871588955286716`. 
And when translating back from HCT, if chroma is below this calculated limit, if you set hue to `209.5429359788321`, you translate achromatic colors back quite nicely.

<img width="1339" alt="Screenshot 2023-01-23 at 12 55 33 PM" src="https://user-images.githubusercontent.com/1055125/214137001-8b08ca6f-71c7-4ede-8b91-be99c63593b6.png">

I think what I've prototyped is actually pretty usable at this point. I think this proves you could probably implement a workable solution here and have it play pretty nicely with Color.js' expectations.

The long and short of it is that:

1. 1st CAM16 has to be implemented here.
2. HCT requires the environment to be set correctly.
3. You just need to calculate L\* from Lab D65. You can get away with just calculating L\* without having to translate a and b.
4. A simple bisect can work to calculate J, but you are probably limited to SDR color spaces. You probably need to clamp the upper and lower bounds of T to be within 0 - 100 when converting back.
5. You can calculate achromatic colors as chroma scales linearly with lightness.
6. When converting achromatic colors back, you really should use ~209.5 as the hue to get the best round-trip results.

I'm certain I need to do even more testing, but I think this provides enough info to get HCT working. I'm sure there is room for improvement, but the above is probably the minimum needed to get this working pretty decently.

**Comment by facelessuser** [comment]
I take it back, I had not graphed the entire response. Chroma responds in an exponential way. I am currently using a 3-degree polynomial. It is probably about 0.0x close. I'm sure this could be improved. It seems okay for now. Anyways, I'm done dumping my findings 🙂. I think there is enough info here. I'll have to spend time ironing out the fine details.

**Comment by facelessuser** [comment]
So, here's the proof of concept live: https://facelessuser.github.io/coloraide-extras/playground/?code=from%20coloraide_extras%2eeverything%20import%20ColorAll%20as%20Color%0Acoloraide%2e__version__%0Acoloraide_extras%2e__version__%0AColor%2esteps%28%5B%27black%27%2C%20%27orange%27%2C%20%27white%27%5D%2C%20steps%3D12%2C%20space%3D%27hct%27%29%0AColor%2einterpolate%28%5B%27blue%27%2C%20%27yellow%27%5D%2C%20space%3D%27hct%27%29%0Adp3%20%3D%20Color%28%22display-p3%22%2C%20%5B0%2C%201%2C%200%5D%29%2econvert%28%27hct%27%29%0Adp3%2C%20dp3%2econvert%28%27display-p3%27%29%2econvert%28%27hct%27%29

<img width="1342" alt="Screenshot 2023-01-25 at 11 56 24 AM" src="https://user-images.githubusercontent.com/1055125/214657209-2c646a64-6001-4bb5-b36d-af94b1d0b0af.png">

It roundtrips fairly decent (I think precision drops a bit at times with `a98-rgb`). We have to iterate to get that precision. as we are simply bisecting to get that CAM16 J to get us back to XYZ. Not a cheap conversion, but it does work with any SDR color space, wide gamut included. I don't think the Material Color Utilities allows anything other than sRGB. HDR lightness will get clamped so we can search our way back to XYZ.

Source that got us here: https://github.com/facelessuser/coloraide-extras/blob/main/coloraide_extras/spaces/hct.py
CAM16 source: https://github.com/facelessuser/coloraide-extras/blob/main/coloraide_extras/spaces/cam16_ucs.py

I'm sure there are optimizations to help convert back quicker, but that may be a task for another week. I imagine a plugin in Color.js should be doable with all this information for those brave enough 🙃.

**Comment by facelessuser** [comment]
One thing to note, if you wanted to match some of the Material Color Utility results when they set a specific tone, it would probably require a gamut mapping algorithm that reduces chroma in HCT. Their library is very sRGB specific. When you set a color in their library, they clamp chroma to the sRGB gamut. What I've implemented allows wide gamuts as well, and if you gamut map a color with LCh or even OkLCh, you will get different results only because they clamp their chroma in HCT.

I probably don't have the CAM16 ∆E tuned right, but generally, the color is pretty close to what Material .

<img width="669" alt="Screenshot 2023-01-26 at 7 54 19 AM" src="https://user-images.githubusercontent.com/1055125/214868295-7083fa31-aadd-4136-918d-d98e7fe0ea4e.png">

**Comment by facelessuser** [comment]
Tonal pallets seem to generate quite well using HCT as the gamut mapping color space.

<img width="1345" alt="Screenshot 2023-01-27 at 12 03 05 PM" src="https://user-images.githubusercontent.com/1055125/215172720-466140a4-bdff-4acd-b841-441352e1ae82.png">

Color channels match the Material lib, but in some cases, there can be a +/- 1 difference for a given color channel (that's measured in a range of 0 - 255). This is simply because their RGB color matrix uses far less precision. If we made a special RGB color space to match exactly what they do, I imagine we'd get exactly the same results, but it simply isn't worth the effort. Change the RGB matrix for one color space, and you'll change the output of another color space converting back and forth. I guess, if you absolutely had to have your values match Material, you could just import Material Color Utilities.

You can play with tone generation [here](https://facelessuser.github.io/coloraide-extras/playground/?code=c%20%3D%20Color%28%27hct%27%2C%20%5B266%2C%2062%2C%2050%5D%29%0Atones%20%3D%20%5B0%2C%2010%2C%2020%2C%2030%2C%2040%2C%2050%2C%2060%2C%2070%2C%2080%2C%2090%2C%2095%2C%20100%5D%0AHtmlSteps%28%5Bc%2eset%28%27tone%27%2C%20tone%29%2econvert%28%27srgb%27%29%2eto_string%28hex%3DTrue%2C%20fit%3D%27hct-chroma%27%29%20for%20tone%20in%20tones%5D%29).

If I'm feeling ambitious, I might see how much effort it is to port this over to colorjs.io, but if not, all the code is available.

**Comment by facelessuser** [comment]
So I've spent some time coding up an implementation of HCT and the necessary code needed for tonal palettes in color.js. This implements the CAM16 model with a JMh color space to verify the model. It has the HCT color space. It implements a distancing algorithm and a gamut mapping method in HCT. With all of this together, we are able to create HCT tonal palettes.  

```js
> const { default: Color } = require("colorjs.io");
undefined
> let tones = [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 95, 100]
undefined
> let c = new Color('blue').to('hct')
undefined
> tones.map(tone => {return c.clone().set('t', tone).toGamut({space: 'srgb', method: 'hct'}).to('srgb').toString({format: 'hex'})})
[
  '#000',    '#00006e',
  '#0000ac', '#0000ef',
  '#333dff', '#5964ff',
  '#7c84ff', '#9da3ff',
  '#bec2ff', '#e0e0ff',
  '#f1efff', '#fff'
]
``` 

One caveat is that there will be no achromatic hue handling. If undefined values are used for chroma and hue in HCT or CAM16 JMh, they will resolve to 0 and you will not get an achromatic color. This is just due to how CAM16, and in turn HCT, works; chroma and hue matter for HCT achromatic colors. This can likely be solved down the road, but I'll leave that as a separate issue.

```js
> new Color('white').to('hct').toString()
'color(hct 209.54 2.8716 100)'
```

I'll try and clean up the code and submit a PR. I'll probably break it up into smaller PRs.

**Comment by facelessuser** [comment]
Full prototype here: https://github.com/facelessuser/color.js/commit/a072617514fee0e66b838873f8948a37827b3251

**Comment by svgeesus** [comment]
Closed by https://github.com/color-js/color.js/pull/380 thanks to @facelessuser
