### ISSUE TITLE
8.7 million is rather larger than 3 million

### ISSUE THREAD

**Issue by svgeesus** [color-js/color.js#609]
Colorjs.io [says](https://colorjs.io/):

> Over [3 million total npm downloads](https://limonte.dev/total-npm-downloads/?package=colorjs.io)!

This remains true, although the link currently says 

> [colorjs.io](https://npmjs.com/package/colorjs.io) was downloaded [8,788,840](https://npm-stat.com/charts.html?package=colorjs.io) times.

I suggest we update the text to say Over 8 million.

**Comment by LeaVerou** [comment]
I just updated it to say over 9 (since it's currently at 8.9 so it will only take 1-2 more days to cross 9 given we're at 500k installs per week)

Ideally we'd want to find an automated way to do this (maybe even a build step that scrapes https://limonte.dev/total-npm-downloads/?package=colorjs.io )

**Comment by MysteryBlokHed** [comment]
This could probably be done with GitHub workflows and the `https://api.npmjs.org/downloads/` endpoint. I can look into writing a workflow sometime tomorrow
